name: Trigger Tests for BDK-FFI Latest Commit
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-bdk-jvm-test ]

permissions: {}

jobs:
  test:
    name: "Run unit tests against the latest commit on bdk-ffi"
    runs-on: ubuntu-24.04

    services:
      bitcoin-regtest:
        image: ghcr.io/thunderbiscuit/podman-regtest-infinity-pro:0.4.0
        ports:
          - 18443:18443
          - 18444:18444
          - 3002:3002
          - 60401:60401
        # The container initialization step will wait until everything is ready before allowing other steps to run
        options: >-
          --health-cmd "test $(bitcoin-cli -regtest -rpcuser=regtest -rpcpassword=password getblockcount) -gt 100"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 20

    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: "Update bdk-ffi submodule to latest"
        run: |
          cd ./bdk-ffi/ \
          && git fetch origin \
          && git checkout master \
          && git pull origin master \
          && echo "Testing commit: $(git log -1 --pretty=format:'%h %s (author: %an)')"

      - name: "Cache"
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}

      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: "Build library"
        run: bash ./scripts/build-linux-x86_64.sh --skip-submodule-update

      - name: "Run tests and build examples"
        run: |
          ./gradlew test
          ./gradlew :examples:build
